/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sigpb.DigitallySigned', null, global);
goog.exportSymbol('proto.sigpb.DigitallySigned.HashAlgorithm', null, global);
goog.exportSymbol('proto.sigpb.DigitallySigned.SignatureAlgorithm', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sigpb.DigitallySigned = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sigpb.DigitallySigned, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.sigpb.DigitallySigned.displayName = 'proto.sigpb.DigitallySigned';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sigpb.DigitallySigned.prototype.toObject = function(opt_includeInstance) {
  return proto.sigpb.DigitallySigned.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sigpb.DigitallySigned} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sigpb.DigitallySigned.toObject = function(includeInstance, msg) {
  var f, obj = {
    hashAlgorithm: jspb.Message.getFieldWithDefault(msg, 1, 0),
    signatureAlgorithm: jspb.Message.getFieldWithDefault(msg, 2, 0),
    signature: msg.getSignature_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sigpb.DigitallySigned}
 */
proto.sigpb.DigitallySigned.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sigpb.DigitallySigned;
  return proto.sigpb.DigitallySigned.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sigpb.DigitallySigned} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sigpb.DigitallySigned}
 */
proto.sigpb.DigitallySigned.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sigpb.DigitallySigned.HashAlgorithm} */ (reader.readEnum());
      msg.setHashAlgorithm(value);
      break;
    case 2:
      var value = /** @type {!proto.sigpb.DigitallySigned.SignatureAlgorithm} */ (reader.readEnum());
      msg.setSignatureAlgorithm(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sigpb.DigitallySigned.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sigpb.DigitallySigned.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sigpb.DigitallySigned} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sigpb.DigitallySigned.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHashAlgorithm();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSignatureAlgorithm();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSignature_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sigpb.DigitallySigned.HashAlgorithm = {
  NONE: 0,
  SHA256: 4
};

/**
 * @enum {number}
 */
proto.sigpb.DigitallySigned.SignatureAlgorithm = {
  ANONYMOUS: 0,
  RSA: 1,
  ECDSA: 3
};

/**
 * optional HashAlgorithm hash_algorithm = 1;
 * @return {!proto.sigpb.DigitallySigned.HashAlgorithm}
 */
proto.sigpb.DigitallySigned.prototype.getHashAlgorithm = function() {
  return /** @type {!proto.sigpb.DigitallySigned.HashAlgorithm} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.sigpb.DigitallySigned.HashAlgorithm} value */
proto.sigpb.DigitallySigned.prototype.setHashAlgorithm = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional SignatureAlgorithm signature_algorithm = 2;
 * @return {!proto.sigpb.DigitallySigned.SignatureAlgorithm}
 */
proto.sigpb.DigitallySigned.prototype.getSignatureAlgorithm = function() {
  return /** @type {!proto.sigpb.DigitallySigned.SignatureAlgorithm} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.sigpb.DigitallySigned.SignatureAlgorithm} value */
proto.sigpb.DigitallySigned.prototype.setSignatureAlgorithm = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional bytes signature = 3;
 * @return {string}
 */
proto.sigpb.DigitallySigned.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes signature = 3;
 * This is a type-conversion wrapper around `getSignature()`
 * @return {string}
 */
proto.sigpb.DigitallySigned.prototype.getSignature_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSignature()));
};


/**
 * optional bytes signature = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSignature()`
 * @return {!Uint8Array}
 */
proto.sigpb.DigitallySigned.prototype.getSignature_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSignature()));
};


/** @param {!(string|Uint8Array)} value */
proto.sigpb.DigitallySigned.prototype.setSignature = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


goog.object.extend(exports, proto.sigpb);
