/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require("google-protobuf");
var goog = jspb;
var global = Function("return this")();

goog.exportSymbol("proto.entrypb.LogEntry", null, global);
goog.exportSymbol("proto.entrypb.MapEntry", null, global);
goog.exportSymbol("proto.entrypb.Operation", null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.entrypb.MapEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.entrypb.MapEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.entrypb.MapEntry.displayName = "proto.entrypb.MapEntry";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.entrypb.MapEntry.prototype.toObject = function(opt_includeInstance) {
    return proto.entrypb.MapEntry.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.entrypb.MapEntry} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.entrypb.MapEntry.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        domain: jspb.Message.getFieldWithDefault(msg, 1, ""),
        cert: jspb.Message.getFieldWithDefault(msg, 2, "")
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.entrypb.MapEntry}
 */
proto.entrypb.MapEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.entrypb.MapEntry();
  return proto.entrypb.MapEntry.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.entrypb.MapEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.entrypb.MapEntry}
 */
proto.entrypb.MapEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setDomain(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCert(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.entrypb.MapEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.entrypb.MapEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.entrypb.MapEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.entrypb.MapEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getCert();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
};

/**
 * optional string domain = 1;
 * @return {string}
 */
proto.entrypb.MapEntry.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/** @param {string} value */
proto.entrypb.MapEntry.prototype.setDomain = function(value) {
  jspb.Message.setField(this, 1, value);
};

/**
 * optional string cert = 2;
 * @return {string}
 */
proto.entrypb.MapEntry.prototype.getCert = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/** @param {string} value */
proto.entrypb.MapEntry.prototype.setCert = function(value) {
  jspb.Message.setField(this, 2, value);
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.entrypb.LogEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.entrypb.LogEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.entrypb.LogEntry.displayName = "proto.entrypb.LogEntry";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.entrypb.LogEntry.prototype.toObject = function(opt_includeInstance) {
    return proto.entrypb.LogEntry.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.entrypb.LogEntry} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.entrypb.LogEntry.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        domain: jspb.Message.getFieldWithDefault(msg, 1, ""),
        operation: jspb.Message.getFieldWithDefault(msg, 2, 0),
        cert: jspb.Message.getFieldWithDefault(msg, 3, "")
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.entrypb.LogEntry}
 */
proto.entrypb.LogEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.entrypb.LogEntry();
  return proto.entrypb.LogEntry.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.entrypb.LogEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.entrypb.LogEntry}
 */
proto.entrypb.LogEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setDomain(value);
        break;
      case 2:
        var value = /** @type {!proto.entrypb.Operation} */ (reader.readEnum());
        msg.setOperation(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setCert(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.entrypb.LogEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.entrypb.LogEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.entrypb.LogEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.entrypb.LogEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getOperation();
  if (f !== 0.0) {
    writer.writeEnum(2, f);
  }
  f = message.getCert();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
};

/**
 * optional string domain = 1;
 * @return {string}
 */
proto.entrypb.LogEntry.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/** @param {string} value */
proto.entrypb.LogEntry.prototype.setDomain = function(value) {
  jspb.Message.setField(this, 1, value);
};

/**
 * optional Operation operation = 2;
 * @return {!proto.entrypb.Operation}
 */
proto.entrypb.LogEntry.prototype.getOperation = function() {
  return /** @type {!proto.entrypb.Operation} */ (jspb.Message.getFieldWithDefault(
    this,
    2,
    0
  ));
};

/** @param {!proto.entrypb.Operation} value */
proto.entrypb.LogEntry.prototype.setOperation = function(value) {
  jspb.Message.setField(this, 2, value);
};

/**
 * optional string cert = 3;
 * @return {string}
 */
proto.entrypb.LogEntry.prototype.getCert = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/** @param {string} value */
proto.entrypb.LogEntry.prototype.setCert = function(value) {
  jspb.Message.setField(this, 3, value);
};

/**
 * @enum {number}
 */
proto.entrypb.Operation = {
  CREATE: 0,
  UPDATE: 1,
  DELETE: 2
};

goog.object.extend(exports, proto.entrypb);
