version: "3"
services:
  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD="trillian_db_pwd"
    networks:
      - trillian
  ilsdb:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD="trillian_db_pwd"
    networks:
      - trillian
  db-seed:
    build:
      context: ../..
      dockerfile: ./Project/ils/src/storage/db/Dockerfile_db_seed
    environment:
      - RESET_DB=${RESET_DB}
      - DB_USER=root
      - DB_PASSWORD="trillian_db_pwd"
      - NODE_ENV=${NODE_ENV}
    networks:
      - trillian
  trillian-log-server:
    build:
      context: ../..
      dockerfile: ./Project/ils/src/storage/trillian/Dockerfile_log_server
    restart: always # retry while mysql is starting up
    networks:
      - trillian
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - mysql
    environment:
      - DB_USER=root
      - DB_PASSWORD="trillian_db_pwd"
      - DB_DATABASE=${DB_DATABASE}
      - LOG_LEVEL=${LOG_LEVEL}
      - GLOG_minloglevel=${GLOG_minloglevel}
  trillian-map-server:
    build:
      context: ../..
      dockerfile: ./Project/ils/src/storage/trillian/Dockerfile_map_server
    restart: always # retry while mysql is starting up
    networks:
      - trillian
    ports:
      - "8093:8090"
      - "8094:8091"
    depends_on:
      - mysql
    environment:
      - DB_USER=root
      - DB_PASSWORD="trillian_db_pwd"
      - DB_DATABASE=${DB_DATABASE}
      - LOG_LEVEL=${LOG_LEVEL}
      - GLOG_minloglevel=${GLOG_minloglevel}
  trillian-log-signer:
    build:
      context: ../..
      dockerfile: ./Project/ils/src/storage/trillian/Dockerfile_log_signer
    restart: always # retry while mysql is starting up
    networks:
      - trillian
    ports:
      - "8092:8096"
    depends_on:
      - mysql
    environment:
      - DB_USER=root
      - DB_PASSWORD="trillian_db_pwd"
      - DB_DATABASE=${DB_DATABASE}
      - LOG_LEVEL=${LOG_LEVEL}
      - GLOG_minloglevel=${GLOG_minloglevel}
    logging:
      driver: none
  tls-server:
    restart: always
    build:
      context: ../
      dockerfile: ils/src/storage/tls_server/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - trillian
  ils:
    environment:
      - ILS_SERVER=${ILS_SERVER}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - RESET_DB=${RESET_DB}
      - NODE_ENV=${NODE_ENV}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_DATABASE}
      - KEYFILE=${KEYFILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_SERVER=trillian-log-server:8090
      - MAP_SERVER=trillian-map-server:8093
      - ILS_DB_HOST=ilsdb
      - ILS_DB_PORT=3306
      - TLS_SERVER_HOST=tls-server
      - TLS_SERVER_PORT=8082
    volumes:
      - ./build:/app/ils/build
    build:
      context: ../
      dockerfile: ils/Dockerfile
    restart: always
    networks:
      - public
      - trillian
    ports:
      - "${DEBUG:-9230}:${DEBUG:-9230}"
      - "8095:8095"
      - "${PORT:-3003}:${PORT:-3003}"
    depends_on:
      - ilsdb
      - tls-server
      - trillian-log-server
      - trillian-map-server
    logging:
      driver: ${ILS_LOG}
networks:
  public:
    external:
      name: crappi-net
  trillian:
